// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Texnokaktus.ProgOlymp.Api.DataAccess.Context;

#nullable disable

namespace Texnokaktus.ProgOlymp.Api.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329145205_Add Internal Users")]
    partial class AddInternalUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronym")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PersonalDataConsent")
                        .HasColumnType("bit");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Snils")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("ContestId", "UserId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UserId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("RegistrationFinish")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RegistrationStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.InternalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Login");

                    b.ToTable("InternalUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeprecated = false,
                            Login = "progolymp26-1",
                            Password = "azjcLgyXJv"
                        },
                        new
                        {
                            Id = 2,
                            IsDeprecated = false,
                            Login = "progolymp26-2",
                            Password = "b8z2jntRwz"
                        },
                        new
                        {
                            Id = 3,
                            IsDeprecated = false,
                            Login = "progolymp26-3",
                            Password = "2NMAbpzgQR"
                        },
                        new
                        {
                            Id = 4,
                            IsDeprecated = false,
                            Login = "progolymp26-4",
                            Password = "MEn8Hqn4UQ"
                        },
                        new
                        {
                            Id = 5,
                            IsDeprecated = false,
                            Login = "progolymp26-5",
                            Password = "T2tcR5HVbf"
                        },
                        new
                        {
                            Id = 6,
                            IsDeprecated = false,
                            Login = "progolymp26-6",
                            Password = "z2zXnhvFC8"
                        },
                        new
                        {
                            Id = 7,
                            IsDeprecated = false,
                            Login = "progolymp26-7",
                            Password = "EfRfadqAH2"
                        },
                        new
                        {
                            Id = 8,
                            IsDeprecated = false,
                            Login = "progolymp26-8",
                            Password = "wGsuGTMub7"
                        },
                        new
                        {
                            Id = 9,
                            IsDeprecated = false,
                            Login = "progolymp26-9",
                            Password = "3fYLTvd6xV"
                        },
                        new
                        {
                            Id = 10,
                            IsDeprecated = false,
                            Login = "progolymp26-10",
                            Password = "s7LLRugyrx"
                        },
                        new
                        {
                            Id = 11,
                            IsDeprecated = false,
                            Login = "progolymp26-11",
                            Password = "bpBevLM8tN"
                        },
                        new
                        {
                            Id = 12,
                            IsDeprecated = false,
                            Login = "progolymp26-12",
                            Password = "yc7zwrkBF5"
                        },
                        new
                        {
                            Id = 13,
                            IsDeprecated = false,
                            Login = "progolymp26-13",
                            Password = "p9zV3Kbe65"
                        },
                        new
                        {
                            Id = 14,
                            IsDeprecated = false,
                            Login = "progolymp26-14",
                            Password = "vsuFNyFNXQ"
                        },
                        new
                        {
                            Id = 15,
                            IsDeprecated = false,
                            Login = "progolymp26-15",
                            Password = "WmYNXYArw6"
                        },
                        new
                        {
                            Id = 16,
                            IsDeprecated = false,
                            Login = "progolymp26-16",
                            Password = "Q8Me5d6fms"
                        },
                        new
                        {
                            Id = 17,
                            IsDeprecated = false,
                            Login = "progolymp26-17",
                            Password = "Td7wnGbHqW"
                        },
                        new
                        {
                            Id = 18,
                            IsDeprecated = false,
                            Login = "progolymp26-18",
                            Password = "r2neJRTrVa"
                        },
                        new
                        {
                            Id = 19,
                            IsDeprecated = false,
                            Login = "progolymp26-19",
                            Password = "qJJ7j8Dc5k"
                        },
                        new
                        {
                            Id = 20,
                            IsDeprecated = false,
                            Login = "progolymp26-20",
                            Password = "3DAJaepkyH"
                        },
                        new
                        {
                            Id = 21,
                            IsDeprecated = false,
                            Login = "progolymp26-21",
                            Password = "hGpmUuwtua"
                        },
                        new
                        {
                            Id = 22,
                            IsDeprecated = false,
                            Login = "progolymp26-22",
                            Password = "AbmFcMjVJw"
                        },
                        new
                        {
                            Id = 23,
                            IsDeprecated = false,
                            Login = "progolymp26-23",
                            Password = "Qg9FKcekgm"
                        },
                        new
                        {
                            Id = 24,
                            IsDeprecated = false,
                            Login = "progolymp26-24",
                            Password = "JD37UJxhba"
                        },
                        new
                        {
                            Id = 25,
                            IsDeprecated = false,
                            Login = "progolymp26-25",
                            Password = "XWp3Vcmh7t"
                        },
                        new
                        {
                            Id = 26,
                            IsDeprecated = false,
                            Login = "progolymp26-26",
                            Password = "aRFsQVbJK5"
                        });
                });

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultAvatar")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Application", b =>
                {
                    b.HasOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Contest", "Contest")
                        .WithMany("Applications")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Participation", "FinalStageParticipation", b1 =>
                        {
                            b1.Property<int>("ApplicationId")
                                .HasColumnType("int");

                            b1.Property<long>("ContestUserId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset?>("Finish")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int?>("InternalUserId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("Start")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("State")
                                .HasColumnType("int");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Participation", "PreliminaryStageParticipation", b1 =>
                        {
                            b1.Property<int>("ApplicationId")
                                .HasColumnType("int");

                            b1.Property<long>("ContestUserId")
                                .HasColumnType("bigint");

                            b1.Property<DateTimeOffset?>("Finish")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int?>("InternalUserId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("Start")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("State")
                                .HasColumnType("int");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Teacher", "Teacher", b1 =>
                        {
                            b1.Property<int>("ApplicationId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Patronym")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("School")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.OwnsOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.ThirdPerson", "Parent", b1 =>
                        {
                            b1.Property<int>("ApplicationId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Patronym")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("Contest");

                    b.Navigation("FinalStageParticipation");

                    b.Navigation("Parent")
                        .IsRequired();

                    b.Navigation("PreliminaryStageParticipation");

                    b.Navigation("Region");

                    b.Navigation("Teacher")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Contest", b =>
                {
                    b.OwnsOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.ContestStage", "FinalStage", b1 =>
                        {
                            b1.Property<int>("ContestId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("ContestFinish")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset>("ContestStart")
                                .HasColumnType("datetimeoffset");

                            b1.Property<long>("Duration")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("State")
                                .HasColumnType("int");

                            b1.Property<long>("YandexContestId")
                                .HasColumnType("bigint");

                            b1.HasKey("ContestId");

                            b1.ToTable("Contests");

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.OwnsOne("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.ContestStage", "PreliminaryStage", b1 =>
                        {
                            b1.Property<int>("ContestId")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset?>("ContestFinish")
                                .HasColumnType("datetimeoffset");

                            b1.Property<DateTimeOffset>("ContestStart")
                                .HasColumnType("datetimeoffset");

                            b1.Property<long>("Duration")
                                .HasColumnType("bigint");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("State")
                                .HasColumnType("int");

                            b1.Property<long>("YandexContestId")
                                .HasColumnType("bigint");

                            b1.HasKey("ContestId");

                            b1.ToTable("Contests");

                            b1.WithOwner()
                                .HasForeignKey("ContestId");
                        });

                    b.Navigation("FinalStage");

                    b.Navigation("PreliminaryStage");
                });

            modelBuilder.Entity("Texnokaktus.ProgOlymp.Api.DataAccess.Entities.Contest", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
